### ISSUE TITLE
how to use this repo in order to train nmt for custom dataset?

### ISSUE THREAD

**Issue by kr-sundaram** [ghchen18/leca#1]
Thanks for making this repository public!

I am new to machine translation and want to use this repositry for training NMT for my use case but i am not sure how to do.

Could you please let me know how can i use this in order to train, evaluate and generate MT predictions on new data?

**Comment by ghchen18** [comment]
Hi, this repo is based on the [fairseq repo](https://github.com/pytorch/fairseq), it provides examples related to [translation](https://github.com/pytorch/fairseq/tree/master/examples/translation) and [scaling_nmt](https://github.com/pytorch/fairseq/tree/master/examples/scaling_nmt). You can follow these examples.
