### ISSUE TITLE
An error in training

### ISSUE THREAD

**Issue by edwardelric1202** [ghchen18/leca#12]
Hi, I got an error when I just started training, as the log below:

RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [128, 32, 1536]], which is output 0 of AddBackward0, is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

my running environment is: 
python 3.6.9
pytorch 1.7.0
I wonder that if it caused by the difference of pytorch version? could you just provide your running environment? Thanks!

**Comment by ghchen18** [comment]
Hi, the env is the same with the official fairseq repo [v0.6.1](https://github.com/pytorch/fairseq/tree/v0.6.1), It says 'Currently fairseq requires PyTorch version >= 1.0.0', I think pytorch=1.0.0 is OK.
