### ISSUE TITLE
disturb

### ISSUE THREAD

**Issue by jhkd-kevin** [ghchen18/leca#3]
I am so sorry to disturb you. If I want to Repetition the experiment, the only thing I need to do is "bash run.sh" like Readme?

**Comment by ghchen18** [comment]
Thanks for your question.  Before 'bash run.sh', you should install fairseq, preprocess your dataset and follow the instructions in the run.sh file. You may need to revise the variables in the run.sh, such as $fseq, $datadir.  Then you can run the code by 'bash run.sh'. I will update the README to include more information.
