### ISSUE TITLE
a problem with train.py

### ISSUE THREAD

**Issue by Haojin-Hu** [ghchen18/leca#6]
File "leca-master/fairseq/data/language_pair_dataset.py", line 145, in __getitem__
assert self.sep_idx not in self.src[index] 
AssertionError

can you give me a help?

**Comment by ghchen18** [comment]
The preprocess.py in this repo should be used for data processing. when you print the self.sep_idx, it should be 4. The used special tokens in the dictionary is different than that of official fairseq.

**Comment by Haojin-Hu** [comment]
trank you！a star for you

**Comment by Haojin-Hu** [comment]
How should I set up to run directly on the GPU？

**Comment by Haojin-Hu** [comment]
Can you provide us with more guidance on the training process? I found that your processing is completely different from fairseq. You wrote your own preprocess.py. The files preprocessed using fairseq cannot be run on your code. Hope You can update a new deadme

**Comment by ghchen18** [comment]
I have revised the README according to your suggestion. Do you have any suggestions about the guidance on the training process?

**Comment by Haojin-Hu** [comment]
Thank you, if I find a problem during the debugging process, I will contact you
