### ISSUE TITLE
ｉｓｓｕｅ

### ISSUE THREAD

**Issue by jhkd-kevin** [ghchen18/leca#7]
As I follow you step, commend "bash run.sh" works, but It seem like training on the CPU, Ｉ　ｗｏｎｄｅｒ　ｈｏｗ　ｃａｎ　Ｉ　ｔｒａｉｎｉｎｇ　ｏｎ　ｔｈｅ　ＧＰＵ？

**Comment by ghchen18** [comment]
The code can work with GPU automatically (See train.py:L35). You can check your GPU in python by `torch.cuda.is_available()`, and you can also check other settings.
