### ISSUE TITLE
issue2

### ISSUE THREAD

**Issue by jhkd-kevin** [ghchen18/leca#9]
Thanks for your help. As I follow your step I finish the preprocess.py however as I use **bash run.sh** 
It occurred that :OSError: **Model file not found:checkpoint_best_bleu.pt**
I used to finish the translation of fairseq, I don't know how can I avoid the problem "checkpoint" in leca
Wish you can help me

**Comment by ghchen18** [comment]
The model has to be trained first before it is tested. You can check the path where you store your model files.
